version: 0.0.{build}
assembly_info:
  patch: true
  file: '**\SolutionInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
build:
  verbosity: minimal