version: 0.0.{build}
configuration: Release
assembly_info:
  patch: true
  file: '**\SolutionInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
before_build:
- ps: >-
    nuget restore

    Invoke-WebRequest http://telligent.com/files/downloads/TelligentCommunity-8.5.7.46581.zip -OutFile TelligentCommunity.zip

    &7z.exe e TelligentCommunity.Zip -oTelligentEvolutionBinaries web\bin

build:
  verbosity: minimal
artifacts:
- path: TableOfContents\bin\Release\AlexCrome.Telligent.TableOfContents.dll